version: "3"
services:
  torrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
      - WEBUI_PORT=9000
    volumes:
      - /mnt/storage/torrent/configs/qbittorrent:/config
      - /mnt/storage/torrent/downloads:/downloads
    restart: unless-stopped
    
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - /mnt/storage/torrent/configs/radarr:/config
      - /mnt/storage/torrent/watch/movies:/movies
      - /mnt/storage/torrent/downloads:/downloads
    ports:
      - 9001:7878
    restart: unless-stopped 

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - /mnt/storage/torrent/configs/sonarr:/config
      - /mnt/storage/torrent/watch/tvshows:/tv
      - /mnt/storage/torrent/downloads:/downloads
    ports:
      - 9002:8989
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022
    volumes:
      - /mnt/storage/torrent/configs/bazarr:/config
      - /mnt/storage/torrent/watch/movies:/movies
      - /mnt/storage/torrent/watch/tvshows:/tv
    ports:
      - 9003:6767
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/storage/torrent/configs/jackett:/config
      - /mnt/storage/torrent/downloads/blackhole:/downloads
    ports:
      - 9004:9117
    restart: unless-stopped

  unpackerr:
    image: golift/unpackerr:latest
    container_name: unpackerr
    volumes:
      # You need at least this one volume mapped so Unapckerr can find your files to extract.
      # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
      - /mnt/storage/torrent/downloads:/downloads
    restart: always
    # Get the user:group correct so unpackerr can read and write to your files.
    user: 1000:1000
    # What you see below are defaults. You only need to include things you change.
    environment:
      - TZ=America/Sao_Paulo
      # General config
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=http://192.168.0.3:9002
      - UN_SONARR_0_API_KEY=eaa6a8bf29524bdcb9ae8ea7c4993ea9
      - UN_SONARR_0_PATHS_0=/downloads
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://192.168.0.3:9001
      - UN_RADARR_0_API_KEY=62d9e1dfafe448d6aa9919c14f077a90
      - UN_RADARR_0_PATHS_0=/downloads
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m

    security_opt:
      - no-new-privileges:true

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022
      - PLEX_CLAIM=claim-sdJtnu-TixNb2cUrW5nF
    volumes:
      - /mnt/storage/torrent/configs/plex:/config
      - /mnt/storage/torrent/watch/tvshows:/tv
      - /mnt/storage/torrent/watch/movies:/movies
    restart: unless-stopped
